CREATE TABLE myNewDB.Users (UserID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, LastName VARCHAR(255), FirstName VARCHAR(255), Address VARCHAR(255), City VARCHAR(255));
Query OK, 0 rows affected (0.20 sec)

